version: '3.8'

services:
  user:
    build: .
    env_file:
      - .env
    restart: always
    hostname: user
    ports:
      - 3002:3002
    expose:
      - 3002
    networks:
      - sass-campanha
    depends_on:
      - db

  user-db:
    image: mysql:8.0.29
    hostname: user-db
    environment:
      MYSQL_ROOT_PASSWORD: "!1- * mysqlrootpass * -1!"
      MYSQL_DATABASE: "userdb"
    ports:
      - 3306:3306
    networks:
      - sass-campanha

networks:
  sass-campanha:
    name: sass-campanha-network
